In [8]:
import numpy as np
data=np.array([[1,12,3],[1,4,5]])
print(data)

[[ 1 12  3]
 [ 1  4  5]]


In [9]:
import numpy as np
a = np.array([1, 2, 3])
print(a * 2)


[2 4 6]


In [13]:
import numpy as np
data=np.array([1,2,3,44,55,8])
print(data)

[ 1  2  3 44 55  8]


In [15]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [17]:
np.ones(3)


array([1., 1., 1.])

In [10]:
import numpy as np
np.arange(2, 20,3)


array([ 2,  5,  8, 11, 14, 17])

In [17]:
import numpy as np
np.random.rand(3)


array([0.67065373, 0.48439394, 0.87390665])

In [19]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [21]:
arr = np.array([2, 4, 6])

print(arr + 2)
print(arr * 3)


[4 6 8]
[ 6 12 18]


In [23]:
arr = np.array([10, 20, 30, 40])

print(arr > 20)
print(arr == 30)
print(arr != 10)


[False False  True  True]
[False False  True False]
[False  True  True  True]


In [25]:
a = np.array([True, False, True])
b = np.array([False, False, True])

print(np.logical_and(a, b))
print(np.logical_or(a, b))
print(np.logical_not(a))


[False False  True]
[ True False  True]
[False  True False]


In [26]:
a=22
print(a)

22


In [27]:
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))


100
25.0
40
10
11.180339887498949


In [28]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=0))  # column-wise
print(np.sum(arr, axis=1))  # row-wise


[5 7 9]
[ 6 15]


In [31]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [32]:
arr = np.array([1.2, 3.7, 4.5])

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))


[1. 4. 4.]
[1. 3. 4.]
[2. 4. 5.]


In [33]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1])
print(arr[1:4])


20
[20 30 40]


In [34]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0, 1])
print(arr[:, 1])


2
[2 5]


In [39]:
arr = np.array([1,2,3,4,5,6])

print(arr.shape)

new_arr = arr.reshape(2, 3)
print(new_arr)


(6,)
[[1 2 3]
 [4 5 6]]


In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate((a, b)))


[1 2 3 4 5 6]


In [43]:
arr = np.array([1,2,3,4,5,6])

print(np.split(arr, 3))


[array([1, 2]), array([3, 4]), array([5, 6])]


In [44]:
arr = np.array([40, 10, 30, 20])

print(np.sort(arr))


[10 20 30 40]


In [45]:
arr = np.array([10, 20, 30, 20])

print(np.where(arr == 20))


(array([1, 3]),)


In [53]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])

print(np.union1d(a,b))
print(np.intersect1d(a,b))
s1=(np.setdiff1d(a,b))
s2=(np.setdiff1d(b,a))
print(np.concatenate((s1,s2)))


[1 2 3 4 5 6]
[3 4]
[1 2 5 6]


In [54]:
a = np.array([1,2,3])

b = a.copy()
c = a.view()

a[0] = 99

print(b)
print(c)


[1 2 3]
[99  2  3]
